version: '3.4'

services:
  rickmortyapi:
    image: rickmortyapi
    container_name: rickmortyapi-pull
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    links:
     - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:16.1
    container_name: postgres-rickmorty
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rickmorty
    ports:
      - "15432:5432"

