version: '2.0'

services:
  rickmorty-api:
    image: ${PROJECT_NAME}-api:${PROJECT_VER}
    container_name: ${PROJECT_NAME}-pull
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    links:
     - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:16.1
    container_name: ${PROJECT_NAME}-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rickmorty
    ports:
      - "${PORT}:5432"

