version: '2.0'

services:
  postgres:

    image: postgres:16.1
    container_name: rickmorty-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rickmorty
    ports:
      - "15432:5432"
    networks:
     - rickmorty-network

  rickmorty-api:
    image: rickmorty-api
    container_name: rickmorty-etl
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    networks:
     - rickmorty-network
    volumes:
      - .:/app

networks:
  rickmorty-network:
    driver: bridge
