version: '2.0'

services:
  postgres:
    image: postgres:16.1
    container_name: ${PROJECT_NAME}-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rickmorty
    ports:
      - "${PORT}:5432"
    networks:
     - ${PROJECT_NAME}-network

  rickmorty-api:
    image: ${PROJECT_NAME}-api:${PROJECT_VER}
    container_name: ${PROJECT_NAME}-etl
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    networks:
     - ${PROJECT_NAME}-network
    volumes:
      - .:/app
    links:
     - postgres

networks:
  rickmorty-network:
    driver: bridge
